{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='usgs.gov', port=80): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88922a22e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"}